// export { createApp } from './createApp'
export { h } from './h'
export { renderSlots } from './renderSlots'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { provider, inject } from './apiInject'
export { createReander } from './render'
